remove node 12 from appveyor
because the ts component build does not work

```
browserify:components
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00A6EF3A v8::internal::Heap::PageFlagsAreConsistent+3050
 2: 00A65690 v8::internal::Heap::CollectGarbage+1200
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! ungit@1.5.20 build: `node ./scripts/build.js`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the ungit@1.5.20 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

https://ci.appveyor.com/project/FredrikNoren/ungit/builds/42714629/job/0jjh13quhmdioidx